import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useAtom } from 'jotai'
import { testAtom } from '../store'

import { Test } from '../components/Test'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [{ darkmode }, setTest] = useAtom(testAtom)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <button
          className='button'
          onClick={() =>
            setTest((prevState) => ({
              ...prevState,
              darkmode: !prevState.darkmode,
            }))
          }
        >
          Toggle Global Theme
        </button>
        <p>{darkmode ? 'dark' : 'light'}</p>
        <Test />
      </main>
    </>
  )
}
